import '../models/local/roleModel.dart';
import '../models/local/userModel.dart';

List<UserModel> userData = [
  UserModel(
    id: "1",
    name: 'Fougeret',
    firstname: 'Alice',
    email: 'john.doe@example.com',
    mobileNumber: '+123456789',
    adress: '123 Main Street, Cityville',
    roles: [
      RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "2",
    name: 'Aviva',
    firstname: 'Charles',
    email: 'jane.smith@example.com',
    mobileNumber: '+987654321',
    adress: '456 Park Avenue, Townsville',
    roles: [
       RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "3",
    name: 'Axel',
    firstname: 'Bernard',
    email: 'alice.brown@example.com',
    mobileNumber: '+111222333',
    adress: '789 Elm Street, Villageton',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "4",
    name: 'Bénédicte',
    firstname: 'Choux',
    email: 'david.johnson@example.com',
    mobileNumber: '+444555666',
    adress: '321 Oak Avenue, Hamletville',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "5",
    name: 'Céile',
    firstname: 'Guilla',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "6",
    name: 'Christophe',
    firstname: 'Serre',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "7",
    name: 'Cloé',
    firstname: 'Bertrand',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
       RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "8",
    name: 'Clothide',
    firstname: 'Guerin',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "9",
    name: 'Clothide',
    firstname: 'Debain',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "10",
    name: 'Delphine',
    firstname: 'Lazreg',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "11",
    name: 'Didier',
    firstname: 'Laurent',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "12",
    name: 'Emma',
    firstname: 'Vallet',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "13",
    name: 'Eric',
    firstname: 'Marradossou',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
       RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "14",
    name: 'Grégory',
    firstname: 'Lecompte',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
       RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "15",
    name: 'Isabelle',
    firstname: 'Brasseur',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
       RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "16",
    name: 'Jean-Marc',
    firstname: 'Ayace',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
       RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "17",
    name: 'Jérôme',
    firstname: 'Lan',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "18",
    name: 'Karine',
    firstname: 'Nedoncelle',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "19",
    name: 'Karine',
    firstname: 'Smaoui',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "20",
    name: 'Laure',
    firstname: 'Baudouin',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
      RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "21",
    name: 'Laurianne',
    firstname: 'Hochedez',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
       RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "22",
    name: 'Mael',
    firstname: 'Miranda',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "23",
    name: 'Maeva',
    firstname: 'Villoria',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
      RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "24",
    name: 'Magali',
    firstname: 'Boussion',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "25",
    name: 'Mireille',
    firstname: 'Lattier',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "26",
    name: 'Mounir',
    firstname: 'ElMai',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
      RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "27",
    name: 'Nathalie',
    firstname: 'Girardin',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
       RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "28",
    name: 'Sarah',
    firstname: 'Mension',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
       RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "29",
    name: 'Sidonie',
    firstname: 'Catteau',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
      RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "30",
    name: 'Stéphane',
    firstname: 'Jamme',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 1,
        name: 'Observateur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
    UserModel(
    id: "31",
    name: 'Fabien',
    firstname: 'Rozec',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "32",
    name: 'Julia',
    firstname: 'Toscano',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "33",
    name: 'Kevin',
    firstname: 'Bergeron',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "34",
    name: 'Grégory',
    firstname: 'Silla',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "35",
    name: 'Florent',
    firstname: 'Beau',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "36",
    name: 'Camille',
    firstname: 'Casteran',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "37",
    name: 'Quentin',
    firstname: 'Casteran',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "38",
    name: 'Raymond',
    firstname: 'Viala',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "39",
    name: 'Clément',
    firstname: 'Kaux',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "40",
    name: 'Marie-Claire',
    firstname: 'Gomez',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "41",
    name: 'Yann',
    firstname: 'Corbobesse',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "42",
    name: 'Franck',
    firstname: 'Alary',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "43",
    name: 'Peggy',
    firstname: 'Fournial',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "44",
    name: 'Alexandra',
    firstname: 'Gigou',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "45",
    name: 'Vincent',
    firstname: 'Bardinal',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "46",
    name: 'Mathieu',
    firstname: 'Lascève',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "47",
    name: 'Emma',
    firstname: 'Herman',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "48",
    name: 'Marie-Jo',
    firstname: 'Noulin',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "49",
    name: 'Marie',
    firstname: 'Lamaze',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "50",
    name: 'Mathieu',
    firstname: 'Imbert',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "51",
    name: 'Axel',
    firstname: 'Berrin',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "52",
    name: 'Emma',
    firstname: 'Hermann',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
      UserModel(
    id: "53",
    name: 'Jérémy',
    firstname: 'Migliore',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
        RoleModel(
        id: 2,
        name: 'référent',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
  UserModel(
    id: "54",
    name: 'Anne',
    firstname: 'Settimeli',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
    UserModel(
    id: "54",
    name: 'Geoffrey',
    firstname: 'Gillet',
    email: 'emma.taylor@example.com',
    mobileNumber: '+777888999',
    adress: '555 Pine Street, Countryside',
    roles: [
       RoleModel(
        id: 3,
        name: 'patrouilleur',
        description: 'Administrator Role',
        enabled: true,
        isSysRole: true,
      ),
    ],
  ),
];
